### Shared configuration for all services backup ###
x-backup-service: &backup-service
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - GIT_USER_NAME=${GIT_USER_NAME:-Developer}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-dev@example.com}
      - GIT_DEFAULT_BRANCH=${GIT_DEFAULT_BRANCH:-main}
      - GIT_TOKEN=${GIT_TOKEN}
  volumes:
    - ./volumes/backup_logs:/var/log/backup_influxdb
    - ./config:/app/config
  networks:
    - backup-network
  environment:
    - PYTHONPATH=/app

### Services ###
services:
  backup-influxdb: # InfluxDB server for development/testing
    image: influxdb:1.8
    container_name: backup-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
    profiles:
      - development
    networks:
      - backup-network

  backup-loki:
    image: grafana/loki
    container_name: backup-loki
    user: "root"
    ports:
      - "3100:3100"
    volumes:
      - ./volumes/loki/config.yaml:/etc/loki/local-config.yaml
      - ./volumes/loki/data:/var/lib/loki
    environment:
      - LOKI_PORT=3100
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml -config.expand-env=true
    networks:
      - backup-network

  backup-grafana: # Grafana server for development/testing
    image: grafana/grafana:latest
    container_name: backup-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
    profiles:
      - development
    networks:
      - backup-network

  backup-service-dev: # Backup service for development
    container_name: backup-service-dev
    <<: *backup-service
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Usar el stage de development
      args:
        - GIT_USER_NAME=${GIT_USER_NAME:-Developer}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL:-dev@example.com}
        - GIT_DEFAULT_BRANCH=${GIT_DEFAULT_BRANCH:-main}
    volumes:
      - ./:/app/  # Montar todo el proyecto para desarrollo
      - ./volumes/backup_logs:/var/log/backup_influxdb # Path de ficheros .logs configurados en .config/*.yaml
      - /var/run/docker.sock:/var/run/docker.sock  # Acceso a Docker desde dentro del contenedor
    environment:
      - PYTHONPATH=/app
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEVELOPMENT=true
      - GIT_TOKEN=${GIT_TOKEN}
    profiles:
      - development
    # El stage development ya tiene sleep infinity como default
    # Permitir capabilities para desarrollo y acceso a Docker
    cap_add:
      - SYS_PTRACE
    privileged: true  # Necesario para acceso completo a Docker

  backup-service-prod: # Backup service for production
    container_name: backup-service-prod
    <<: *backup-service
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # Usar el stage de production (imagen mínima)
    profiles:
      - production
    restart: unless-stopped
    # El stage production ya tiene el comando correcto como default

### Networks ###
networks:
  backup-network:
    driver: bridge
    name: ${INFLUXDB_NETWORK:-influxdb-network}
